UPDATE tickers SET name='PT Bank Central Asia Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='BBCA';
UPDATE tickers SET name='PT Bank Rakyat Indonesia (Persero) Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='BBRI';
UPDATE tickers SET name='PT Bank Mandiri (Persero) Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='BMRI';
UPDATE tickers SET name='PT Bank Negara Indonesia (Persero) Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='BBNI';
UPDATE tickers SET name='PT Astra International Tbk', sector='Industrials', industry='Conglomerates' WHERE ticker='ASII';
UPDATE tickers SET name='Perusahaan Perseroan (Persero) PT Telekomunikasi Indonesia Tbk', sector='Communication Services', industry='Telecom Services' WHERE ticker='TLKM';
UPDATE tickers SET name='PT Unilever Indonesia Tbk', sector='Consumer Defensive', industry='Household & Personal Products' WHERE ticker='UNVR';
UPDATE tickers SET name='PT Indofood CBP Sukses Makmur Tbk', sector='Consumer Defensive', industry='Packaged Foods' WHERE ticker='ICBP';
UPDATE tickers SET name='PT Indofood Sukses Makmur Tbk', sector='Consumer Defensive', industry='Packaged Foods' WHERE ticker='INDF';
UPDATE tickers SET name='PT GoTo Gojek Tokopedia Tbk', sector='Technology', industry='Software - Infrastructure' WHERE ticker='GOTO';
UPDATE tickers SET name='PT Alamtri Resources Indonesia Tbk', sector='Energy', industry='Thermal Coal' WHERE ticker='ADRO';
UPDATE tickers SET name='PT Bukit Asam (Persero) Tbk', sector='Energy', industry='Thermal Coal' WHERE ticker='PTBA';
UPDATE tickers SET name='PT Indo Tambangraya Megah Tbk', sector='Energy', industry='Thermal Coal' WHERE ticker='ITMG';
UPDATE tickers SET name='PT United Tractors Tbk', sector='Basic Materials', industry='Other Industrial Metals & Mining' WHERE ticker='UNTR';
UPDATE tickers SET name='PT Amman Mineral Internasional Tbk', sector='Basic Materials', industry='Other Precious Metals & Mining' WHERE ticker='AMMN';
UPDATE tickers SET name='PT Barito Renewables Energy Tbk', sector='Utilities', industry='Utilities - Renewable' WHERE ticker='BREN';
UPDATE tickers SET name='PT Petrindo Jaya Kreasi Tbk', sector='Energy', industry='Thermal Coal' WHERE ticker='CUAN';
UPDATE tickers SET name='PT Pertamina Geothermal Energy Tbk', sector='Utilities', industry='Utilities - Renewable' WHERE ticker='PGEO';
UPDATE tickers SET name='PT Chandra Asri Pacific Tbk', sector='Basic Materials', industry='Specialty Chemicals' WHERE ticker='TPIA';
UPDATE tickers SET name='PT Bayan Resources Tbk.', sector='Energy', industry='Thermal Coal' WHERE ticker='BYAN';
UPDATE tickers SET name='PT ESSA Industries Indonesia Tbk.', sector='Basic Materials', industry='Chemicals' WHERE ticker='ESSA';
UPDATE tickers SET name='PT Barito Pacific Tbk', sector='Basic Materials', industry='Chemicals' WHERE ticker='BRPT';
UPDATE tickers SET name='PT Kalbe Farma Tbk.', sector='Healthcare', industry='Drug Manufacturers - General' WHERE ticker='KLBF';
UPDATE tickers SET name='PT Mitra Keluarga Karyasehat Tbk', sector='Healthcare', industry='Medical Care Facilities' WHERE ticker='MIKA';
UPDATE tickers SET name='PT Charoen Pokphand Indonesia Tbk', sector='Consumer Defensive', industry='Farm Products' WHERE ticker='CPIN';
UPDATE tickers SET name='PT Japfa Comfeed Indonesia Tbk', sector='Consumer Defensive', industry='Farm Products' WHERE ticker='JPFA';
UPDATE tickers SET name='PT. Indika Energy Tbk', sector='Energy', industry='Thermal Coal' WHERE ticker='INDY';
UPDATE tickers SET name='PT Medco Energi Internasional Tbk', sector='Energy', industry='Oil & Gas E&P' WHERE ticker='MEDC';
UPDATE tickers SET name='PT Energi Mega Persada Tbk', sector='Energy', industry='Oil & Gas E&P' WHERE ticker='ENRG';
UPDATE tickers SET name='PT Harum Energy Tbk', sector='Energy', industry='Thermal Coal' WHERE ticker='HRUM';
UPDATE tickers SET name='PT Sumber Alfaria Trijaya Tbk', sector='Consumer Defensive', industry='Grocery Stores' WHERE ticker='AMRT';
UPDATE tickers SET name='PT Midi Utama Indonesia Tbk', sector='Consumer Defensive', industry='Grocery Stores' WHERE ticker='MIDI';
UPDATE tickers SET name='PT Map Aktif Adiperkasa Tbk', sector='Consumer Cyclical', industry='Specialty Retail' WHERE ticker='MAPA';
UPDATE tickers SET name='PT. Mitra Adiperkasa Tbk', sector='Consumer Cyclical', industry='Department Stores' WHERE ticker='MAPI';
UPDATE tickers SET name='PT Aspirasi Hidup Indonesia Tbk', sector='Consumer Cyclical', industry='Specialty Retail' WHERE ticker='ACES';
UPDATE tickers SET name='PT Surya Citra Media Tbk', sector='Communication Services', industry='Broadcasting' WHERE ticker='SCMA';
UPDATE tickers SET name='PT Elang Mahkota Teknologi Tbk', sector='Communication Services', industry='Broadcasting' WHERE ticker='EMTK';
UPDATE tickers SET name='PT Bukalapak.com Tbk.', sector='Consumer Cyclical', industry='Internet Retail' WHERE ticker='BUKA';
UPDATE tickers SET name='PT Bank Jago Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='ARTO';
UPDATE tickers SET name='PT Bank Syariah Indonesia Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='BRIS';
UPDATE tickers SET name='PT Bank Tabungan Negara (Persero) Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='BBTN';
UPDATE tickers SET name='PT Bank Danamon Indonesia Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='BDMN';
UPDATE tickers SET name='PT Bank CIMB Niaga Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='BNGA';
UPDATE tickers SET name='PT Bank OCBC NISP Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='NISP';
UPDATE tickers SET name='PT Bank Pan Indonesia Tbk', sector='Financial Services', industry='Banks - Regional' WHERE ticker='PNBN';
UPDATE tickers SET name='PT Jasa Marga (Persero) Tbk', sector='Industrials', industry='Infrastructure Operations' WHERE ticker='JSMR';
UPDATE tickers SET name='PT Wijaya Karya (Persero) Tbk', sector='Industrials', industry='Engineering & Construction' WHERE ticker='WIKA';
UPDATE tickers SET name='PT PP (Persero) Tbk', sector='Industrials', industry='Engineering & Construction' WHERE ticker='PTPP';
UPDATE tickers SET name='PT Adhi Karya (Persero) Tbk', sector='Industrials', industry='Engineering & Construction' WHERE ticker='ADHI';
UPDATE tickers SET name='PT Waskita Karya (Persero) Tbk' WHERE ticker='WSKT';
UPDATE tickers SET name='PT Semen Indonesia (Persero) Tbk', sector='Basic Materials', industry='Building Materials' WHERE ticker='SMGR';
UPDATE tickers SET name='PT Indocement Tunggal Prakarsa Tbk', sector='Basic Materials', industry='Building Materials' WHERE ticker='INTP';
UPDATE tickers SET name='PT Summarecon Agung Tbk', sector='Real Estate', industry='Real Estate - Development' WHERE ticker='SMRA';
UPDATE tickers SET name='PT Ciputra Development Tbk', sector='Real Estate', industry='Real Estate - Development' WHERE ticker='CTRA';
UPDATE tickers SET name='PT Bumi Serpong Damai Tbk', sector='Real Estate', industry='Real Estate - Development' WHERE ticker='BSDE';
UPDATE tickers SET name='PT Pakuwon Jati Tbk', sector='Real Estate', industry='Real Estate - Diversified' WHERE ticker='PWON';
UPDATE tickers SET name='PT Alam Sutera Realty Tbk', sector='Real Estate', industry='Real Estate - Development' WHERE ticker='ASRI';
UPDATE tickers SET name='PT AKR Corporindo Tbk', sector='Energy', industry='Oil & Gas Refining & Marketing' WHERE ticker='AKRA';
UPDATE tickers SET name='PT Perusahaan Gas Negara (Persero) Tbk', sector='Utilities', industry='Utilities - Regulated Gas' WHERE ticker='PGAS';
UPDATE tickers SET name='PT XLSMART Telecom Sejahtera Tbk', sector='Communication Services', industry='Telecom Services' WHERE ticker='EXCL';
UPDATE tickers SET name='PT Indosat Ooredoo Hutchison Tbk', sector='Communication Services', industry='Telecom Services' WHERE ticker='ISAT';
UPDATE tickers SET name='PT Sarana Menara Nusantara Tbk.', sector='Real Estate', industry='Real Estate Services' WHERE ticker='TOWR';
UPDATE tickers SET name='PT Tower Bersama Infrastructure Tbk', sector='Communication Services', industry='Telecom Services' WHERE ticker='TBIG';
UPDATE tickers SET name='PT Dayamitra Telekomunikasi Tbk.', sector='Communication Services', industry='Telecom Services' WHERE ticker='MTEL';
UPDATE tickers SET name='PT Vale Indonesia Tbk', sector='Basic Materials', industry='Other Industrial Metals & Mining' WHERE ticker='INCO';
UPDATE tickers SET name='PT Antam (Persero) Tbk', sector='Basic Materials', industry='Gold' WHERE ticker='ANTM';
UPDATE tickers SET name='PT Merdeka Copper Gold Tbk', sector='Basic Materials', industry='Other Industrial Metals & Mining' WHERE ticker='MDKA';
UPDATE tickers SET name='PT TIMAH Tbk', sector='Basic Materials', industry='Other Industrial Metals & Mining' WHERE ticker='TINS';
UPDATE tickers SET name='PT Samudera Indonesia Tbk', sector='Industrials', industry='Marine Shipping' WHERE ticker='SMDR';
UPDATE tickers SET name='PT Temas Tbk.', sector='Industrials', industry='Marine Shipping' WHERE ticker='TMAS';
UPDATE tickers SET name='PT Pelayaran Nelly Dwi Putri Tbk', sector='Industrials', industry='Marine Shipping' WHERE ticker='NELY';
UPDATE tickers SET name='PT Industri Jamu dan Farmasi Sido Muncul Tbk', sector='Consumer Defensive', industry='Packaged Foods' WHERE ticker='SIDO';
UPDATE tickers SET name='PT Mayora Indah Tbk', sector='Consumer Defensive', industry='Packaged Foods' WHERE ticker='MYOR';
UPDATE tickers SET name='PT Ultrajaya Milk Industry & Trading Company Tbk', sector='Consumer Defensive', industry='Beverages - Non-Alcoholic' WHERE ticker='ULTJ';
UPDATE tickers SET name='PT Sariguna Primatirta Tbk', sector='Consumer Defensive', industry='Beverages - Non-Alcoholic' WHERE ticker='CLEO';
UPDATE tickers SET name='PT Nippon Indosari Corpindo Tbk', sector='Consumer Defensive', industry='Packaged Foods' WHERE ticker='ROTI';
UPDATE tickers SET name='PT Integra Indocabinet Tbk', sector='Consumer Cyclical', industry='Furnishings, Fixtures & Appliances' WHERE ticker='WOOD';
UPDATE tickers SET name='PT Indah Kiat Pulp & Paper Tbk', sector='Basic Materials', industry='Paper & Paper Products' WHERE ticker='INKP';
UPDATE tickers SET name='PT Pabrik Kertas Tjiwi Kimia Tbk', sector='Basic Materials', industry='Paper & Paper Products' WHERE ticker='TKIM';
UPDATE tickers SET name='PT Sinar Mas Agro Resources and Technology Tbk', sector='Consumer Defensive', industry='Farm Products' WHERE ticker='SMAR';
UPDATE tickers SET name='PT Perusahaan Perkebunan London Sumatra Indonesia Tbk', sector='Consumer Defensive', industry='Farm Products' WHERE ticker='LSIP';
UPDATE tickers SET name='Adaro Andalan Indonesia Tbk.', sector='Energy', industry='Thermal Coal' WHERE ticker='AADI';
UPDATE tickers SET name='PT Alamtri Minerals Indonesia Tbk', sector='Basic Materials', industry='Coking Coal' WHERE ticker='ADMR';
UPDATE tickers SET name='PT Bumi Resources Tbk', sector='Energy', industry='Thermal Coal' WHERE ticker='BUMI';
UPDATE tickers SET name='PT Darma Henwa Tbk', sector='Energy', industry='Thermal Coal' WHERE ticker='DEWA';
UPDATE tickers SET name='PT Hartadinata Abadi Tbk', sector='Consumer Cyclical', industry='Luxury Goods' WHERE ticker='HRTA';
UPDATE tickers SET name='PT Merdeka Battery Materials Tbk.', sector='Basic Materials', industry='Other Precious Metals & Mining' WHERE ticker='MBMA';
UPDATE tickers SET name='PT Solusi Sinergi Digital Tbk', sector='Technology', industry='Information Technology Services' WHERE ticker='WIFI';
UPDATE tickers SET name='TRIL.JK,0P0000EOL4,0' WHERE ticker='TRIL';
UPDATE tickers SET name='PT Trada Alam Minera Tbk' WHERE ticker='TRAM';
UPDATE tickers SET name='PT Hanson International Tbk' WHERE ticker='MYRX';
UPDATE tickers SET name='PT Rimo International Lestari Tbk' WHERE ticker='RIMO';
UPDATE tickers SET name='PT Quantum Clovera Investama Tbk', sector='Financial Services', industry='Asset Management' WHERE ticker='KREN';
UPDATE tickers SET name='SUGI.JK,0P0000BT07,0' WHERE ticker='SUGI';
UPDATE tickers SET name='PT Sinergi Megah Internusa Tbk' WHERE ticker='NUSA';
