DELETE FROM signal_history WHERE date='2026-07-09';
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('TINS','2026-07-09',5,'FULL LOCK','Skor total tinggi + kualitas kuat + momentum positif');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ADRO','2026-07-09',4,'Solid','Skor total baik dengan fundamental solid');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ESSA','2026-07-09',4,'Solid','Skor total baik dengan fundamental solid');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('JPFA','2026-07-09',4,'Solid','Skor total baik dengan fundamental solid');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BBTN','2026-07-09',4,'Solid','Skor total baik dengan fundamental solid');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BDMN','2026-07-09',4,'Solid','Skor total baik dengan fundamental solid');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ULTJ','2026-07-09',4,'Solid','Skor total baik dengan fundamental solid');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ADMR','2026-07-09',4,'Solid','Skor total baik dengan fundamental solid');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BBCA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BBRI','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BMRI','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BBNI','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('UNVR','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('INDF','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('GOTO','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('PTBA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ITMG','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('PGEO','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('TPIA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BRPT','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('MEDC','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ENRG','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('MAPA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('MAPI','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('SCMA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('EMTK','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BUKA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BRIS','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BNGA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('NISP','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('PWON','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('AKRA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('EXCL','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ISAT','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('TOWR','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('MTEL','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('INCO','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ANTM','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('MDKA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('INKP','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('SMAR','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('LSIP','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('AADI','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('DEWA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('HRTA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('MBMA','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('WIFI','2026-07-09',3,'Sedang Anget','Skor rata-rata, perlu dipantau');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ASII','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('TLKM','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ICBP','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('UNTR','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('AMMN','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BREN','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('CUAN','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('MIKA','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('CPIN','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('INDY','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('HRUM','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('AMRT','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('MIDI','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ACES','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ARTO','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('PNBN','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('JSMR','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ADHI','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('INTP','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('SMRA','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BSDE','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ASRI','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('PGAS','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('TBIG','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('TMAS','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('SIDO','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('MYOR','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('CLEO','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('TKIM','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BUMI','2026-07-09',2,'Dingin','Skor rendah, waspadai pelemahan lanjutan');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('BYAN','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('KLBF','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('WIKA','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('PTPP','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('WSKT','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('SMGR','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('CTRA','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('SMDR','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('NELY','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('ROTI','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('WOOD','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
INSERT INTO signal_history(ticker,date,signal_tier,signal_label,signal_reason) VALUES('KREN','2026-07-09',1,'Awasi','Skor sangat rendah, hindari dulu');
