export const IDX80_TICKERS = [
  "BBCA.JK", "BBRI.JK", "BMRI.JK", "BBNI.JK", "ASII.JK", "TLKM.JK", "UNVR.JK", "ICBP.JK", "INDF.JK", "GOTO.JK",
  "ADRO.JK", "PTBA.JK", "ITMG.JK", "UNTR.JK", "AMMN.JK", "BREN.JK", "CUAN.JK", "PGEO.JK", "TPIA.JK", "BYAN.JK",
  "ESSA.JK",
  "BRPT.JK", "KLBF.JK", "MIKA.JK", "CPIN.JK", "JPFA.JK", "INDY.JK", "MEDC.JK", "ENRG.JK", "HRUM.JK", "AMRT.JK",
  "MIDI.JK", "MAPA.JK", "MAPI.JK", "ACES.JK", "SCMA.JK", "EMTK.JK", "BUKA.JK", "ARTO.JK", "BRIS.JK", "BBTN.JK",
  "BDMN.JK", "BNGA.JK", "NISP.JK", "PNBN.JK", "JSMR.JK", "WIKA.JK", "PTPP.JK", "ADHI.JK", "WSKT.JK", "SMGR.JK",
  "INTP.JK", "SMRA.JK", "CTRA.JK", "BSDE.JK", "PWON.JK", "ASRI.JK", "AKRA.JK", "PGAS.JK", "EXCL.JK", "ISAT.JK",
  "TOWR.JK", "TBIG.JK", "MTEL.JK", "INCO.JK", "ANTM.JK", "MDKA.JK", "TINS.JK", "SMDR.JK", "TMAS.JK", "NELY.JK",
  "SIDO.JK", "MYOR.JK", "ULTJ.JK", "CLEO.JK", "ROTI.JK", "WOOD.JK", "INKP.JK", "TKIM.JK", "SMAR.JK", "LSIP.JK",
  // 💀 TRASH & DEAD STOCKS (To Prove Survivorship Avoidance)
  "TRIL.JK", "TRAM.JK", "MYRX.JK", "RIMO.JK", "KREN.JK", "SUGI.JK", "NUSA.JK"
];

export const IDX30_TICKERS = [
  "ADRO.JK", "AKRA.JK", "AMRT.JK", "ANTM.JK", "ARTO.JK", "ASII.JK", "BBCA.JK", "BBNI.JK", "BBRI.JK", "BMRI.JK",
  "BRIS.JK", "BRPT.JK", "BUKA.JK", "CPIN.JK", "ESSA.JK", "EXCL.JK", "GOTO.JK", "HRUM.JK", "ICBP.JK", "INDF.JK",
  "INTP.JK", "ITMG.JK", "KLBF.JK", "MDKA.JK", "MEDC.JK", "PGAS.JK", "PTBA.JK", "SMGR.JK", "TLKM.JK", "UNTR.JK"
];

export const LQ45_TICKERS = [
  "AADI.JK", "ADMR.JK", "ADRO.JK", "AKRA.JK", "AMMN.JK", "AMRT.JK", "ANTM.JK", "ASII.JK",
  "BBCA.JK", "BBNI.JK", "BBRI.JK", "BBTN.JK", "BMRI.JK", "BRPT.JK", "BUMI.JK", "CPIN.JK",
  "CUAN.JK", "DEWA.JK", "EMTK.JK", "ESSA.JK", "EXCL.JK", "GOTO.JK", "HRTA.JK", "ICBP.JK",
  "INCO.JK", "INDF.JK", "INKP.JK", "ISAT.JK", "ITMG.JK", "JPFA.JK", "KLBF.JK", "MAPI.JK",
  "MBMA.JK", "MDKA.JK", "MEDC.JK", "PGAS.JK", "PGEO.JK", "PTBA.JK", "SCMA.JK", "SMGR.JK",
  "TLKM.JK", "TOWR.JK", "UNTR.JK", "UNVR.JK", "WIFI.JK"
];

// Combined deduplicated universe from all 3 indices
export const COMBINED_TICKERS = [...new Set([
  ...LQ45_TICKERS,
  ...IDX80_TICKERS,
  ...IDX30_TICKERS,
])];
