import {
  BacktestDayData,
  BacktestConfig,
  ProfileWeights,
  ExecutionFees,
  BacktestResult,
  ChartPoint,
  TradeLog,
  DEFAULT_FEES,
  StrategiesInput,
} from "./types";
import { computeDayRankings, pickTopTickersByRank, getCleanTickerList, computeAdaptiveWeights } from "./ranker";
import { detectCrashAlgo, detectRecoveryAlgo } from "./crashDetector";
import dividendSnapshots from "../data/dividend_snapshots.json";
import {
  computeInitialAllocation,
  liquidateHoldings,
  computeGoldPurchase,
  computeGoldSale,
  computeRebalanceSwap,
  computeSellProceeds,
} from "./allocator";
import { computeMetrics } from "./metrics";
import { computeBuyPressureFromMarket } from "./buyPressure";
import { getDividendPerShare } from "./dividendCache";

export function runStrategy(input: StrategiesInput): BacktestResult {
  const { dayData: rawInput, config, profileWeights: inputWeights, universeTickers, fees = DEFAULT_FEES } = input;
  let currentWeights = { ...inputWeights };

  // Fallback rank key for legacy data that lacks `stockNormScores`. Newer data
  // generated by migrate-normscores.ts always has stockNormScores, so the rank
  // recompute branch below handles all profiles with the user's actual weights.
  // Custom profiles (activeProfileId starts with "custom_") and "dividen" fall
  // back to "aman" rank key as a defensive default (data only has Prod/Res).
  const activeProfileKey: "stockRanksProd" | "stockRanksRes" =
    config.activeProfileId === "agresif" ? "stockRanksRes" : "stockRanksProd";

  const dayData: BacktestDayData[] = rawInput.map(d => {
    if (d.stockNormScores && typeof d.stockNormScores === "object") {
      // Backfill missing dividend score from FUNDAMENTAL_SNAPSHOTS (DPS / price)
      // — year data only has Q/G/V/M. Top ~9 IDX stocks have real DPS; rest
      // get a neutral 50 (which collapses to uniform shift under ranking).
      const tickersInDay = Object.keys(d.stockNormScores);
      const year = parseInt(d.date.slice(0, 4), 10);
      const enrichedScores: Record<string, { quality: number; growth: number; value: number; momentum: number; dividend: number }> = {};
      const yields: { ticker: string; y: number }[] = [];
      for (const t of tickersInDay) {
        const ns = d.stockNormScores[t];
        const existing = (ns as any).dividend;
        let yieldPct = 0;
        if (existing === undefined) {
          const dps = (dividendSnapshots as any)[t]?.[year]?.dividend_per_share;
          const price = d.stockPrices?.[t];
          if (dps > 0 && price > 0) {
            yieldPct = (dps / price) * 100;
          }
          yields.push({ ticker: t, y: yieldPct });
        }
        enrichedScores[t] = {
          quality: ns.quality ?? 50,
          growth: ns.growth ?? 50,
          value: ns.value ?? 50,
          momentum: ns.momentum ?? 50,
          dividend: existing ?? 50,
        };
      }
      if (yields.length > 0) {
        yields.sort((a, b) => a.y - b.y);
        const n = yields.length;
        yields.forEach((it, i) => {
          enrichedScores[it.ticker].dividend = (i / Math.max(1, n - 1)) * 95;
        });
      }
      const stockRanks = computeDayRankings(enrichedScores, currentWeights);
      return { ...d, stockRanks };
    }
    return {
      ...d,
      stockRanks: d[activeProfileKey as keyof BacktestDayData] as Record<string, number> || d.stockRanks,
    };
  });

  const filtered = dayData.filter(
    d => d.date >= config.simStartDate && d.date <= config.simEndDate
  );

  if (filtered.length === 0) {
    throw new Error("Tidak ada data dalam rentang tanggal yang dipilih.");
  }

  const cap = config.capital;
  const bufferCash = cap * (config.reserveBufferPct / 100);
  const initialInvestable = cap - bufferCash;

  const cleanIdx80 = getCleanTickerList(universeTickers.idx80);
  const cleanIdx30 = getCleanTickerList(universeTickers.idx30);
  const cleanLq45 = getCleanTickerList(universeTickers.lq45);

  const getUniverseTickers = (): string[] => {
    if (config.universe === "idx80") return cleanIdx80;
    if (config.universe === "idx30") return cleanIdx30;
    if (config.universe === "lq45") return cleanLq45;
    return cleanIdx80;
  };

  const day0 = filtered[0];

  let topTickers: string[];
  if (config.simulationMode === "custom") {
    const customUniverse = (config.customUniverse || []).filter(
      t => day0.stockPrices[t] && day0.stockPrices[t] > 0
    );
    topTickers = customUniverse;
  } else if (config.simulationMode === "algo") {
    topTickers = pickTopTickersByRank(
      day0.stockRanks, day0.stockPrices, getUniverseTickers(), config.topNCount
    );
  } else {
    // adaptive_dca: no topTickers pre-computed; each month-end re-evaluates.
    topTickers = [];
  }

  const initialAlloc = computeInitialAllocation(
    initialInvestable, topTickers, day0.stockPrices, day0.stockVolumes, fees
  );

  let positions = { ...initialAlloc.positions };
  let cash = initialAlloc.cash;
  let goldGrams = 0;
  let inCrashState = false;
  let crashCooldown = 0;
  let totalTransactionVolume = initialAlloc.totalVolume;
  let lastRebalanceMonth = new Date(day0.date).getMonth();
  let pendingTickers = [...initialAlloc.pendingTickers];

  let totalSwaps = 0;
  let totalDividendsEarned = 0;
  let maxVal = cap;
  let maxDrawdownValue = 0;
  // Adaptive DCA tracking — how much cash has been deployed and the BPS
  // history (used by SimulationTab for charting).
  let totalDeployed = config.simulationMode === "adaptive_dca" ? 0 : initialInvestable;
  let lastDeploymentMonth = config.simulationMode === "adaptive_dca"
    ? -1
    : new Date(day0.date).getMonth();
  const bpsHistory: Array<{ date: string; score: number; deployPct: number; action: string }> = [];

  const chartData: ChartPoint[] = [];
  const logs: TradeLog[] = [];

  const initialIhsgPrice = day0.ihsgPrice;
  const initialGoldPrice = day0.goldPrice;

  // A5 fix: incremental IHSG price window — was O(n²) because we called
  // filtered.slice(0, stepIndex + 1).map(...) on every day. For a 1500-day
  // backtest this was ~1.1M iterations. The crash detector only needs the
  // last 60 prices (its own internal slice), so we maintain a single rolling
  // buffer of (up to 60) closing prices that we push to as the loop advances.
  const ihsgRollingWindow: number[] = [day0.ihsgPrice];

  let lastJulyYear = 2019;
  const dailyReturns: number[] = [];
  let lastDayVal = cap;

  const configName = config.simulationMode === "adaptive_dca"
    ? "Adaptive DCA (BPS-driven)"
    : config.activeProfileId === "agresif"
    ? "Agresif (Growth-heavy)"
    : config.activeProfileId === "dividen"
    ? "Dividen (Yield-focused)"
    : "Aman (Quality + Growth)";

  logs.push({
    date: day0.date,
    type: "BUY",
    message: `Inisialisasi portofolio ${topTickers.length} emiten dari ${Object.keys(day0.stockPrices).length} kandidat — alokasi ${(initialAlloc.cash / cap * 100).toFixed(0)}% kas, ${(100 - initialAlloc.cash / cap * 100).toFixed(0)}% saham`,
  });

  const getPointInTimeDate = (date: Date): Date => {
    return new Date(date.getFullYear(), date.getMonth(), date.getDate());
  };

  for (let stepIndex = 0; stepIndex < filtered.length; stepIndex++) {
    const day = filtered[stepIndex];
    const dateObj = new Date(day.date);
    const currentYear = dateObj.getFullYear();
    const currentMonth = dateObj.getMonth();

    // A5: append current IHSG to the rolling window. Cap at 60 to match
    // detectCrashAlgo's own 60-day lookback — anything older is irrelevant.
    ihsgRollingWindow.push(day.ihsgPrice);
    if (ihsgRollingWindow.length > 60) ihsgRollingWindow.shift();

    if (pendingTickers.length > 0) {
      for (let pi = pendingTickers.length - 1; pi >= 0; pi--) {
        const pt = pendingTickers[pi];
        const availPrice = day.stockPrices?.[pt.ticker];
        if (availPrice && availPrice > 0) {
          const entryPrice = availPrice * (1 + fees.slippage);
          const costPerShare = entryPrice * (1 + fees.buyFee);
          let maxLots = Math.floor(pt.capital / (costPerShare * 100));
          let sharesToBuy = maxLots * 100;
          if (sharesToBuy > 0) {
            positions[pt.ticker] = sharesToBuy;
            cash -= sharesToBuy * costPerShare;
            totalTransactionVolume += sharesToBuy * entryPrice;
            logs.push({
              date: day.date,
              type: "BUY",
              message: `Eksekusi #${pt.ticker} ${sharesToBuy} lembar @ Rp ${Math.round(entryPrice).toLocaleString("id-ID")} = Rp ${(sharesToBuy * Math.round(entryPrice)).toLocaleString("id-ID")}`,
            });
          }
          pendingTickers.splice(pi, 1);
        }
      }
    }

    let stocksValue = 0;
    Object.entries(positions).forEach(([ticker, shares]) => {
      const price = day.stockPrices[ticker] || 100;
      stocksValue += shares * price;
    });

    const goldVal = goldGrams * day.goldPrice;
    const todayPortfolioVal = cash + goldVal + stocksValue + bufferCash;

    if (stepIndex > 0) {
      const ret = ((todayPortfolioVal - lastDayVal) / lastDayVal) * 100;
      dailyReturns.push(ret);
    }
    lastDayVal = todayPortfolioVal;

    if (todayPortfolioVal > maxVal) {
      maxVal = todayPortfolioVal;
    } else {
      const dd = ((maxVal - todayPortfolioVal) / maxVal) * 100;
      if (dd > maxDrawdownValue) maxDrawdownValue = dd;
    }

    if (currentYear > lastJulyYear && currentMonth >= 5 && dateObj.getDate() >= 15) {
      let yearlyDividends = 0;
      Object.entries(positions).forEach(([ticker, shares]) => {
        const dps = getDividendPerShare(ticker, dateObj);
        if (dps > 0 && shares > 0) {
          const divPaid = Math.round(shares * dps * 0.90);
          yearlyDividends += divPaid;
        }
      });
      if (yearlyDividends > 0) {
        cash += yearlyDividends;
        totalDividendsEarned += yearlyDividends;
        logs.push({
          date: day.date,
          type: "REBALANCE",
          message: `Dividen tahunan dikreditkan: Rp ${yearlyDividends.toLocaleString("id-ID")} (net 90%) — portfolio value saat ini Rp ${todayPortfolioVal.toLocaleString("id-ID")}`,
        });
      }
      lastJulyYear = currentYear;
    }

    let crashSignaled = false;
    let crashReason = "";

    if (config.enableCrashProtection) {
      if (config.simulationMode === "algo" || config.simulationMode === "custom") {
        const result = detectCrashAlgo(ihsgRollingWindow, day.ihsgPrice, config.crashSensitivity);
        crashSignaled = result.signaled;
        crashReason = result.reason;
      }
    }

    if (crashSignaled && !inCrashState && crashCooldown <= 0) {
      const liq = liquidateHoldings(positions, day.stockPrices, fees);
      logs.push({
        date: day.date,
        type: "CRASH_TRIGGER",
        message: `CRASH: ${crashReason} — likuidasi ${Object.keys(positions).length} posisi, proceeds Rp ${liq.proceeds.toLocaleString("id-ID")} → ${config.safeHavenAsset === "emas" ? "konversi ke emas" : "cash"}`,
      });
      positions = {};
      cash += liq.proceeds;
      totalTransactionVolume += liq.totalVolume;

      inCrashState = true;

      if (config.safeHavenAsset === "emas") {
        const gold = computeGoldPurchase(cash, day.goldPrice);
        goldGrams = gold.goldGrams;
        cash = gold.cash;
      }

      crashCooldown = 20;
    }

    if (inCrashState && crashCooldown <= 0) {
      let recoverySignaled = false;

      if (config.simulationMode === "algo" || config.simulationMode === "custom") {
        const result = detectRecoveryAlgo(ihsgRollingWindow, day.ihsgPrice);
        recoverySignaled = result.signaled;

        if (result.signaled) {
          logs.push({
            date: day.date,
            type: "CRASH_RECOVERY",
            message: `RECOVERY: ${result.reason} — IHSG ${day.ihsgPrice.toLocaleString("id-ID")}`,
          });
        }
      }

      if (recoverySignaled) {
        inCrashState = false;
        let recoveryCash = cash;

        if (goldGrams > 0) {
          const goldSale = computeGoldSale(goldGrams, day.goldPrice);
          recoveryCash += goldSale.cash;
          goldGrams = 0;
        }

        let reentryTickers: string[];
        if (config.simulationMode === "custom") {
          reentryTickers = (config.customUniverse || []).filter(
            t => day.stockPrices[t] && day.stockPrices[t] > 0
          );
        } else if (config.simulationMode === "algo") {
          reentryTickers = pickTopTickersByRank(
            day.stockRanks, day.stockPrices, getUniverseTickers(), config.topNCount
          );
        } else {
          reentryTickers = [];
        }

        const reentryAlloc = computeInitialAllocation(
          recoveryCash, reentryTickers, day.stockPrices, day.stockVolumes, fees
        );

        Object.entries(reentryAlloc.positions).forEach(([t, shares]) => {
          positions[t] = (positions[t] || 0) + shares;
        });
        cash = reentryAlloc.cash;
        totalTransactionVolume += reentryAlloc.totalVolume;
        pendingTickers.push(...reentryAlloc.pendingTickers);

        logs.push({
          date: day.date,
          type: "CRASH_RECOVERY",
          message: `Re-entry ${reentryTickers.length} emiten setelah recovery pasar — alokasi Rp ${recoveryCash.toLocaleString("id-ID")}`,
        });

        crashCooldown = 20;
      }
    }

    if (crashCooldown > 0) crashCooldown--;

    // Adaptive DCA deployment: on month change, compute BPS from historical
    // signals and deploy BPS.deployPct of available cash into top N. Unlike
    // algo mode there is NO monthly rank-based rotation — once deployed,
    // positions are held until crash triggers liquidation.
    if (!inCrashState && config.simulationMode === "adaptive_dca" && currentMonth !== lastDeploymentMonth) {
      lastDeploymentMonth = currentMonth;

      // Compute BPS signals from rolling windows of historical data.
      const lookback21 = Math.max(0, stepIndex - 21);
      const lookback60 = Math.max(0, stepIndex - 60);
      const ihsg21ago = filtered[lookback21].ihsgPrice;
      const ihsgMonthly = day0.ihsgPrice > 0
        ? ((day.ihsgPrice - ihsg21ago) / ihsg21ago) * 100
        : 0;
      const window60 = filtered.slice(lookback60, stepIndex + 1).map(d => d.ihsgPrice);
      const peak60 = window60.length > 0 ? Math.max(...window60) : day.ihsgPrice;
      const drawdown60 = peak60 > 0 ? ((day.ihsgPrice - peak60) / peak60) * 100 : 0;
      const breadthAbove60 = Object.values(day.stockRanks).filter(r => r > 0 && r <= config.topNCount * 3).length;
      const watchlistCount = Object.keys(day.stockRanks).length;
      const riskScore = Math.min(100, Math.max(0, Math.abs(ihsgMonthly) * 4));
      const avgValueScore = Object.keys(day.stockRanks).length > 0
        ? Object.entries(day.stockNormScores || {})
            .reduce((sum, [, ns]) => sum + (ns.value ?? 50), 0) / Math.max(1, Object.keys(day.stockNormScores || {}).length)
        : 50;

      const bps = computeBuyPressureFromMarket(
        ihsgMonthly,
        drawdown60,
        breadthAbove60,
        watchlistCount,
        riskScore,
        avgValueScore,
        false, // isCrisisMode is checked separately; we still allow purchases during recovery
      );
      bpsHistory.push({
        date: day.date,
        score: bps.score,
        deployPct: bps.deployPct,
        action: bps.action,
      });

      // Deploy BPS.deployPct of AVAILABLE cash (not all cash).
      const deployAmount = Math.floor(cash * bps.deployPct / 100);
      if (deployAmount > 0) {
        const topTickersMonth = pickTopTickersByRank(
          day.stockRanks, day.stockPrices, getUniverseTickers(), config.topNCount,
        );
        const alloc = computeInitialAllocation(deployAmount, topTickersMonth, day.stockPrices, day.stockVolumes, fees);
        Object.entries(alloc.positions).forEach(([ticker, newShares]) => {
          positions[ticker] = (positions[ticker] || 0) + newShares;
        });
        cash -= (deployAmount - alloc.cash);
        totalDeployed += deployAmount;
        totalTransactionVolume += alloc.totalVolume;
        logs.push({
          date: day.date,
          type: "BUY",
          message: `[Adaptive DCA] BPS ${bps.score} → ${bps.action.toUpperCase()} → deploy Rp ${deployAmount.toLocaleString("id-ID")} (${bps.deployPct}%) ke ${alloc.positions.length} emiten.`,
        });
      }
    }

    if (!inCrashState && config.enableAdaptiveWeights && day.stockNormScores && stepIndex >= 60) {
      const isMonthChange = currentMonth !== lastRebalanceMonth;
      if (isMonthChange) {
        currentWeights = computeAdaptiveWeights(filtered, stepIndex, 60, currentWeights, config.topNCount);
        const newRanks = computeDayRankings(day.stockNormScores, currentWeights);
        (filtered[stepIndex] as BacktestDayData).stockRanks = newRanks;
      }
    }

    // Adaptive DCA: no monthly rebalancing — positions are held until
    // crash triggers full liquidation. Skip the rebalancing block.
    if (!inCrashState && config.enableCrossover && config.simulationMode === "algo") {
      const ownedTickers = Object.entries(positions)
        .filter(([_, shares]) => shares > 0)
        .map(([ticker]) => ticker);

      const isMonthChange = currentMonth !== lastRebalanceMonth;

      for (const ticker of ownedTickers) {
        const currentRank = day.stockRanks[ticker] || 5;
        const isEmergencyExit = currentRank >= 15;
        const isRoutineExit = isMonthChange && currentRank >= 10;

        if (isEmergencyExit || isRoutineExit) {
          const sellResult = computeSellProceeds(positions[ticker], day.stockPrices[ticker] || 100, fees);
          const swapProceeds = sellResult.proceeds;
          totalTransactionVolume += sellResult.volume;
          delete positions[ticker];

          const topCandidates = pickTopTickersByRank(
            day.stockRanks, day.stockPrices, getUniverseTickers(), config.topNCount
          );
          const swapInTicker = topCandidates.find(t => t !== ticker && (!positions[t] || positions[t] === 0));

          if (swapInTicker) {
            const swapResult = computeRebalanceSwap(
              ticker, swapProceeds, day.stockPrices, day.stockVolumes, swapInTicker, fees
            );

            if (swapResult.shares > 0) {
              positions[swapInTicker] = (positions[swapInTicker] || 0) + swapResult.shares;
              cash += swapResult.cashRemainder;
              totalTransactionVolume += swapResult.totalVolume;
              logs.push({
                date: day.date,
                type: "REBALANCE",
                message: `Swap #${ticker} (rank ${currentRank}) → #${swapInTicker} (rank ${day.stockRanks[swapInTicker] || "?"}), ${swapResult.shares} lot @ Rp ${(day.stockPrices[swapInTicker] || 0).toLocaleString("id-ID")}, proceeds Rp ${swapProceeds.toLocaleString("id-ID")}`,
              });
            } else {
              cash += swapProceeds;
            }
            totalSwaps++;
          } else {
            cash += swapProceeds;
          }
        }
      }

      if (isMonthChange) lastRebalanceMonth = currentMonth;
    }

    if (stepIndex % 8 === 0 || stepIndex === filtered.length - 1) {
      const benchmarkIhsgVal = Math.round((day.ihsgPrice / initialIhsgPrice) * cap);
      const benchmarkGoldVal = Math.round((day.goldPrice / initialGoldPrice) * cap);

      chartData.push({
        date: day.date,
        "Strategi Rebalancer": Math.round(todayPortfolioVal),
        "Benchmark IHSG": benchmarkIhsgVal,
        "Benchmark Emas": benchmarkGoldVal,
        ranks: { ...day.stockRanks },
      });

      if (stepIndex === filtered.length - 1 && day.date < config.simEndDate) {
        chartData.push({
          date: config.simEndDate,
          "Strategi Rebalancer": Math.round(todayPortfolioVal),
          "Benchmark IHSG": benchmarkIhsgVal,
          "Benchmark Emas": benchmarkGoldVal,
          ranks: { ...day.stockRanks },
        });
      }
    }
  }

  const currentPortfolioVal = cash +
    (Object.entries(positions).reduce((sum, [t, s]) => sum + s * (filtered[filtered.length - 1].stockPrices[t] || 100), 0)) +
    (goldGrams * filtered[filtered.length - 1].goldPrice) + bufferCash;

  const lastDayObj = filtered[filtered.length - 1];

  const metrics = computeMetrics({
    cap,
    currentPortfolioVal,
    day0Date: day0.date,
    lastDayDate: lastDayObj.date,
    dailyReturns,
    maxDrawdownValue,
    totalTransactionVolume,
    initialIhsgPrice,
    lastIhsgPrice: lastDayObj.ihsgPrice,
    initialGoldPrice,
    lastGoldPrice: lastDayObj.goldPrice,
  });

  const ihsgFinalValue = Math.round((lastDayObj.ihsgPrice / initialIhsgPrice) * cap);
  const goldFinalValue = Math.round((lastDayObj.goldPrice / initialGoldPrice) * cap);

  const allLogs: TradeLog[] = [
    ...logs,
    {
      date: lastDayObj.date,
      type: "REBALANCE",
      message: `Portfolio akhir: Rp ${currentPortfolioVal.toLocaleString("id-ID")} (${metrics.totalReturnPct >= 0 ? "+" : ""}${metrics.totalReturnPct.toFixed(2)}%) — CAGR ${metrics.cagr.toFixed(2)}% | Sharpe ${metrics.sharpe.toFixed(3)} | Max DD ${maxDrawdownValue.toFixed(2)}%`,
    },
  ];

  return {
    finalValue: Math.round(currentPortfolioVal),
    ihsgFinalValue,
    goldFinalValue,
    totalReturnPct: metrics.totalReturnPct,
    ihsgReturnPct: metrics.ihsgReturnPct,
    goldReturnPct: metrics.goldReturnPct,
    maxDrawdown: maxDrawdownValue,
    totalTrades: totalSwaps,
    totalDividends: totalDividendsEarned,
    cagr: metrics.cagr,
    volatility: metrics.volatility,
    sharpe: metrics.sharpe,
    sortino: metrics.sortino,
    calmar: metrics.calmar,
    winRatePct: metrics.winRatePct,
    turnoverPct: metrics.turnoverPct,
    bench6040FinalVal: metrics.bench6040FinalVal,
    bench6040ReturnPct: metrics.bench6040ReturnPct,
    configName,
    logs: allLogs,
    chartData,
    bpsHistory: bpsHistory.length > 0 ? bpsHistory : undefined,
    totalDeployed: config.simulationMode === "adaptive_dca" ? totalDeployed : undefined,
  };
}

export interface StrategyEvaluation {
  shouldExit: boolean;
  reason: string;
  targetSafeHaven: "emas" | "kas" | null;
}

export function evaluateStrategy(
  config: BacktestConfig,
  marketData: { ihsgPrice: number; peak60?: number; dayRanks?: Record<string, number> }
): StrategyEvaluation {
  if (!config.enableCrashProtection) {
    return { shouldExit: false, reason: "Crash protection disabled", targetSafeHaven: null };
  }

  if (config.simulationMode !== "algo" && config.simulationMode !== "custom") {
    return { shouldExit: false, reason: "Non-algo mode uses own trigger", targetSafeHaven: null };
  }

  if (marketData.peak60 !== undefined) {
    const drop = ((marketData.ihsgPrice - marketData.peak60) / marketData.peak60) * 100;
    if (drop <= -config.crashSensitivity) {
      return {
        shouldExit: true,
        reason: `IHSG dropped ${Math.abs(drop).toFixed(1)}% from 60d peak (threshold: ${config.crashSensitivity}%)`,
        targetSafeHaven: config.safeHavenAsset,
      };
    }
  }

  return { shouldExit: false, reason: "IHSG within tolerance", targetSafeHaven: null };
}

export function shouldTriggerExit(
  ticker: string,
  position: { shares: number; buyPrice: number; currentPrice: number },
  config: BacktestConfig,
  marketData: { ihsgPrice: number; peak60?: number }
): StrategyEvaluation {
  if (!position || position.shares <= 0) {
    return { shouldExit: false, reason: "No position", targetSafeHaven: null };
  }

  const strategy = evaluateStrategy(config, marketData);
  if (strategy.shouldExit) {
    return strategy;
  }

  const drawdown = ((position.currentPrice - position.buyPrice) / position.buyPrice) * 100;
  if (drawdown <= -config.singleSellTrigger) {
    return {
      shouldExit: true,
      reason: `${ticker} dropped ${Math.abs(drawdown).toFixed(1)}% (sell trigger: ${config.singleSellTrigger}%)`,
      targetSafeHaven: config.safeHavenAsset,
    };
  }

  return { shouldExit: false, reason: "Position healthy", targetSafeHaven: null };
}

export function getActiveUniverse(config: BacktestConfig): string[] {
  if (config.simulationMode === "custom") {
    return [...(config.customUniverse || [])];
  }
  return [];
}
