// src/types/DataStatus.ts

/**
 * Enum representing the provenance/status of a piece of market data.
 *
 * - LIVE: data fetched directly from a live provider (GoAPI, Yahoo, etc.)
 * - CACHED: the most recent verified cache file (e.g., data/live_market.json)
 * - STALE: cached data that is older than the freshness threshold
 * - ESTIMATED: data generated by a model/fallback algorithm, not from a provider
 * - CARRIED_FORWARD: synthetic data copied from last known day to fill gaps
 */
export enum DataStatus {
  LIVE = "LIVE",
  CACHED = "CACHED",
  STALE = "STALE",
  ESTIMATED = "ESTIMATED",
  CARRIED_FORWARD = "CARRIED_FORWARD",
}
