import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

const cwd = process.cwd();
const src = join(cwd, "data", "historical_market_data.json");
const outDir = join(cwd, "data", "years");

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

// Pre-2021 data was archived 2026-06. The master historical_market_data.json
// is no longer regenerated by the build pipeline — year files are kept in
// git (2021+ only). If the master is missing, skip split-data gracefully.
if (!existsSync(src)) {
  console.log(`[split-data] SKIP — master file not found: ${src}`);
  console.log(`[split-data] Year files in ${outDir} are kept as-is (2021+ only).`);
  console.log(`[split-data] To re-run, regenerate historical_market_data.json via scripts/fetch_historical_data.ts`);
  process.exit(0);
}

console.log("Reading JSON...");
const raw = readFileSync(src, "utf-8");
const data = JSON.parse(raw);
console.log(`Total records: ${data.length}`);

const years: Record<string, any[]> = {};
for (const rec of data) {
  const year = rec.date.slice(0, 4);
  if (!years[year]) years[year] = [];
  years[year].push(rec);
}

let total = 0;
for (const [year, records] of Object.entries(years).sort()) {
  const filePath = join(outDir, `${year}.json`);
  writeFileSync(filePath, JSON.stringify(records));
  const size = (Buffer.byteLength(JSON.stringify(records)) / 1024 / 1024).toFixed(2);
  console.log(`${year}: ${records.length} records, ${size}MB`);
  total += records.length;
}
console.log(`Done. ${total} records split into ${Object.keys(years).length} year files.`);
